name: Build and Release Flutter Android App

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version of the release (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-and-release:
    name: Build and Release Android APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

        #2 Setup Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

    # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.2
          target: android-35
        #3 Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'

        #4 Install Dependencies
      - name: Install Dependencies
        run: flutter pub get
        
       #6 Building APK
      - name: Build APK
        run: flutter build apk --release
        
        #13 Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.TOKEN }}
